### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by ghost** [paulehoffman/ietf-cli#3]
Hello-

Please tag versioned releases with [git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging). GitHub can then automatically use these to populate [your releases](https://github.com/paulehoffman/ietf-cli/releases). Software packagers everywhere thank you in advance! :)

**Comment by paulehoffman** [comment]
Sorry, I had totally forgotten to do this. I've started doing so today with version 1.17

**Comment by peterhessler4711** [comment]
Ping, time to start re-tagging releases.  Thanks!

**Comment by paulehoffman** [comment]
True; done.
